version: "3.8"

services:
  targets-api:
    image: alexeynaidiuk/targets-api:latest
    build: .
    ports:
      - "8181:8181"
    networks:
      - mynetwork
    env_file:
       - ".env"
#    command:
#      - uvicorn app.main:app --host=${HOST} --port=${PORT}
  db:
    image: postgres:latest
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    networks:
      - mynetwork
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./redis:/data
networks:
  mynetwork:
    name: "mynetwork"
    driver: bridge
