"""empty message

Revision ID: 12c4e5cc1520
Revises: a586ce552fc6
Create Date: 2023-06-21 15:39:34.067572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c4e5cc1520'
down_revision = 'a586ce552fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
