"""empty message

Revision ID: 1bf3127c38b8
Revises: 48d42b79a3d9
Create Date: 2023-07-26 15:57:32.335282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf3127c38b8'
down_revision = '48d42b79a3d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_target_emails_sent_counter'), 'target_emails', ['sent_counter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_emails_sent_counter'), table_name='target_emails')
    # ### end Alembic commands ###
