"""empty message

Revision ID: 353b0ef34d15
Revises: 69b6f52a79cf
Create Date: 2023-06-01 15:56:17.611316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353b0ef34d15'
down_revision = '69b6f52a79cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('total_sent_counter', sa.SMALLINT(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'total_sent_counter')
    # ### end Alembic commands ###
