"""empty message

Revision ID: 35b68443dc52
Revises: 6a23bcafb626
Create Date: 2023-06-09 15:10:26.703007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b68443dc52'
down_revision = '6a23bcafb626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources_info', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_target_emails_email', table_name='target_emails')
    op.drop_index('ix_target_emails_sent_counter', table_name='target_emails')
    op.drop_index('ix_target_emails_source_id', table_name='target_emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_target_emails_source_id', 'target_emails', ['source_id'], unique=False)
    op.create_index('ix_target_emails_sent_counter', 'target_emails', ['sent_counter'], unique=False)
    op.create_index('ix_target_emails_email', 'target_emails', ['email'], unique=False)
    op.alter_column('sources_info', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
