"""empty message

Revision ID: 5b3d94b9a0f8
Revises: 8e9dc7aa014a
Create Date: 2023-06-07 14:34:22.278431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3d94b9a0f8'
down_revision = '8e9dc7aa014a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_stats', 'promo_code',
               existing_type=sa.SMALLINT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_stats', 'promo_code',
               existing_type=sa.String(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
