"""empty message

Revision ID: 6740453c0918
Revises: d054cd8fd032
Create Date: 2023-06-21 15:05:51.704926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6740453c0918'
down_revision = 'd054cd8fd032'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
