"""empty message

Revision ID: 69b6f52a79cf
Revises: d1304ca81a52
Create Date: 2023-05-31 15:22:28.246123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b6f52a79cf'
down_revision = 'd1304ca81a52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
