"""empty message

Revision ID: 6a23bcafb626
Revises: 19ffca6938ae
Create Date: 2023-06-09 14:24:22.526546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a23bcafb626'
down_revision = '19ffca6938ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources_info',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('lang', sa.VARCHAR(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources_info')
    # ### end Alembic commands ###
