"""empty message

Revision ID: 7525780744fd
Revises: 12c4e5cc1520
Create Date: 2023-06-21 15:41:04.600649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7525780744fd'
down_revision = '12c4e5cc1520'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
