"""empty message

Revision ID: 7f504d3ead10
Revises: 5b3d94b9a0f8
Create Date: 2023-06-09 14:07:39.076692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f504d3ead10'
down_revision = '5b3d94b9a0f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'total_sent_counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('total_sent_counter', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
