"""empty message

Revision ID: a586ce552fc6
Revises: 38c9b79675fa
Create Date: 2023-06-21 15:32:40.773445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a586ce552fc6'
down_revision = '38c9b79675fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
