"""empty message

Revision ID: a8db1ef255eb
Revises: 1bf3127c38b8
Create Date: 2023-08-03 16:30:00.517400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8db1ef255eb'
down_revision = '1bf3127c38b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spam_donors', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('spam_donors', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spam_donors', 'updated_at')
    op.drop_column('spam_donors', 'created_at')
    # ### end Alembic commands ###
