"""empty message

Revision ID: aaf29b48a83f
Revises: 
Create Date: 2023-05-31 14:31:21.600879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf29b48a83f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitly_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link_id', sa.VARCHAR(length=14), nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=22), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('spins', sa.SMALLINT(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('available', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spam_donors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('success_count', sa.SMALLINT(), nullable=False),
    sa.Column('fail_count', sa.SMALLINT(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('donor_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('prom_link', sa.VARCHAR(length=22), nullable=False),
    sa.Column('referral_name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('targets_source', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donor_name')
    )
    op.create_table('texts',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('lang', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('text_id', sa.SMALLINT(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_text_id'), 'sources', ['text_id'], unique=False)
    op.create_table('target_emails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=127), nullable=False),
    sa.Column('sent_counter', sa.SMALLINT(), nullable=True),
    sa.Column('source_id', sa.SMALLINT(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_emails_email'), 'target_emails', ['email'], unique=False)
    op.create_index(op.f('ix_target_emails_id'), 'target_emails', ['id'], unique=False)
    op.create_index(op.f('ix_target_emails_sent_counter'), 'target_emails', ['sent_counter'], unique=False)
    op.create_index(op.f('ix_target_emails_source_id'), 'target_emails', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_emails_source_id'), table_name='target_emails')
    op.drop_index(op.f('ix_target_emails_sent_counter'), table_name='target_emails')
    op.drop_index(op.f('ix_target_emails_id'), table_name='target_emails')
    op.drop_index(op.f('ix_target_emails_email'), table_name='target_emails')
    op.drop_table('target_emails')
    op.drop_index(op.f('ix_sources_text_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('texts')
    op.drop_table('spam_donors')
    op.drop_table('referrals')
    op.drop_table('bitly_links')
    # ### end Alembic commands ###
