"""empty message

Revision ID: d054cd8fd032
Revises: 35b68443dc52
Create Date: 2023-06-09 15:11:29.797659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd054cd8fd032'
down_revision = '35b68443dc52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_target_emails_id', table_name='target_emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_target_emails_id', 'target_emails', ['id'], unique=False)
    # ### end Alembic commands ###
