"""empty message

Revision ID: d1304ca81a52
Revises: aaf29b48a83f
Create Date: 2023-05-31 15:20:33.372508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1304ca81a52'
down_revision = 'aaf29b48a83f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
