"""empty message

Revision ID: f53c8b00f1b4
Revises: a8db1ef255eb
Create Date: 2023-11-06 16:15:32.560893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53c8b00f1b4'
down_revision = 'a8db1ef255eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spam_donors', 'donor_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('spam_donors', 'prom_link',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spam_donors', 'prom_link',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=22),
               existing_nullable=False)
    op.alter_column('spam_donors', 'donor_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
